
# Simulation 1.1

Proportion growth (budgets 4 and 8)

```{r}
print_plot1 <- function(network_name,b){
  greedy <- read.csv(paste("sim/c1_", network_name, "_greedy_",b,"_0.1.csv", sep=""))[[1]]
  degree <- read.csv(paste("sim/c1_", network_name, "_degree_",b,"_0.1.csv", sep=""))[[1]]
  pagerank <- read.csv(paste("sim/c1_", network_name, "_pagerank_",b,"_0.1.csv", sep=""))[[1]]
  P_pagerank <- read.csv(paste("sim/c1_", network_name, "_P_pagerank_",b,"_0.1.csv", sep=""))[[1]]
  eigenvector <- read.csv(paste("sim/c1_", network_name, "_eigenvector_",b,"_0.1.csv", sep=""))[[1]]
  betweenness <- read.csv(paste("sim/c1_", network_name, "_betweenness_",b,"_0.1.csv", sep=""))[[1]]
  
  plotname <- paste(network_name,"with b=",b)
  
  ylim <- c(0, 1.0)
  plot(greedy, type = "l", col = "red", xlab = "Time Steps", ylab = "Proportion Infected", main = plotname,  ylim = ylim)
  lines(degree, col = "blue")
  lines(pagerank, col = "green")
  lines(P_pagerank, col = "orange")
  lines(eigenvector, col = "yellow")
  lines(betweenness, col = "gray")
  legend("topright", legend = c("greedy", "degree", "pagerank", "P_pagerank","eigenvector", "betweenness"), col = c("red", "blue", "green", "orange", "yellow","gray"), lty = 1,cex = 0.8)
}
```

```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
b_list <- c(4,8)

network <- "ER"
b<-4

for (network in network_names){
  for (b in b_list){
    print_plot1(network, b)
  }
}
```

# Simulation 1.2

Expected number (budget 4)

```{r}
print_plot2_num_infected <- function(network_name, b) {
  greedy <- read.csv(paste("sim/c1_", network_name, "_greedy_", b, "_0.1.csv", sep = ""))[[2]]
  degree <- read.csv(paste("sim/c1_", network_name, "_degree_", b, "_0.1.csv", sep = ""))[[2]]
  pagerank <- read.csv(paste("sim/c1_", network_name, "_pagerank_", b, "_0.1.csv", sep = ""))[[2]]
  P_pagerank <- read.csv(paste("sim/c1_", network_name, "_P_pagerank_", b, "_0.1.csv", sep = ""))[[2]]
  eigenvector <- read.csv(paste("sim/c1_", network_name, "_eigenvector_", b, "_0.1.csv", sep = ""))[[2]]
  betweenness <- read.csv(paste("sim/c1_", network_name, "_betweenness_", b, "_0.1.csv", sep = ""))[[2]]

  plotname <- paste(network_name, "with b=", b)

  ylim <- c(0, max(max(greedy), max(degree), max(pagerank), max(P_pagerank), max(eigenvector), max(betweenness)))

  plot(greedy, type = "l", col = "red", xlab = "Time Steps", ylab = "Expected Number of Infected Nodes", main = plotname, ylim = ylim)
  lines(degree, col = "blue")
  lines(pagerank, col = "green")
  lines(P_pagerank, col = "orange")
  lines(eigenvector, col = "yellow")
  lines(betweenness, col = "gray")
  legend("topright", legend = c("greedy", "degree", "pagerank", "P_pagerank", "eigenvector", "betweenness"), col = c("red", "blue", "green", "orange", "yellow", "gray"), lty = 1, cex = 0.8)
}
```

```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
b_list <- c(4)

network <- "ER"
b <- 4

for (network in network_names) {
  for (b in b_list) {
    print_plot2_num_infected(network, b)
  }
}
```


# Simulation 1.3

Expected number (budget 4 and alpha = 0.3)

```{r}
print_plot3_num_infected <- function(network_name, b) {
  greedy <- read.csv(paste("sim/c1_", network_name, "_greedy_", b, "_0.3.csv", sep = ""))[[2]]
  degree <- read.csv(paste("sim/c1_", network_name, "_degree_", b, "_0.3.csv", sep = ""))[[2]]
  pagerank <- read.csv(paste("sim/c1_", network_name, "_pagerank_", b, "_0.3.csv", sep = ""))[[2]]
  P_pagerank <- read.csv(paste("sim/c1_", network_name, "_P_pagerank_", b, "_0.3.csv", sep = ""))[[2]]
  eigenvector <- read.csv(paste("sim/c1_", network_name, "_eigenvector_", b, "_0.3.csv", sep = ""))[[2]]
  betweenness <- read.csv(paste("sim/c1_", network_name, "_betweenness_", b, "_0.3.csv", sep = ""))[[2]]

  plotname <- paste(network_name, "with b=", b)

  ylim <- c(0, max(max(greedy), max(degree), max(pagerank), max(P_pagerank), max(eigenvector), max(betweenness)))

  plot(greedy, type = "l", col = "red", xlab = "Time Steps", ylab = "Expected Number of Infected Nodes", main = plotname, ylim = ylim)
  lines(degree, col = "blue")
  lines(pagerank, col = "green")
  lines(P_pagerank, col = "orange")
  lines(eigenvector, col = "yellow")
  lines(betweenness, col = "gray")
  legend("topright", legend = c("greedy", "degree", "pagerank", "P_pagerank", "eigenvector", "betweenness"), col = c("red", "blue", "green", "orange", "yellow", "gray"), lty = 1, cex = 0.8)
}
```

```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
b_list <- c(4)

network <- "ER"
b <- 4

for (network in network_names) {
  for (b in b_list) {
    print_plot3_num_infected(network, b)
  }
}
```

# Simulation 1.4

Greedy vs. p-Pagerank (b = 4 and 8)

```{r}
print_plot4 <- function(network_name){
  
  greedy4 <- read.csv(paste("sim/c1_", network_name, "_greedy_4_0.1.csv", sep=""))[[1]]
  greedy8 <- read.csv(paste("sim/c1_", network_name, "_greedy_4_0.1.csv", sep=""))[[1]]
  P_pagerank4 <- read.csv(paste("sim/c1_", network_name, "_P_pagerank_8_0.1.csv", sep=""))[[1]]
  P_pagerank8 <- read.csv(paste("sim/c1_", network_name, "_P_pagerank_8_0.1.csv", sep=""))[[1]]

  
  plotname <- paste(network_name)
  ylim <- c(0, 1.0)
  plot(greedy4, type = "l", col = "red", xlab = "Time Steps", ylab = "Proportion Infected", main = plotname, ylim = ylim)
  lines(greedy8, col = "red", lty = 2) # dotted line for greedy(b=20)
  lines(P_pagerank4, col = "blue")
  lines(P_pagerank8, col = "blue", lty = 2) # dotted line for P_pagerank(b=8)
  
  legend("topright", legend = c("greedy(b=4)", "greedy(b=8)", "P_pagerank(b=4)", "P_pagerank(b=8)"), col = c("red", "red", "blue", "blue"), lty = c(1, 2, 1, 2), cex = 0.8)
}
```


```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")

for (i in 1:length(network_names)) {
    print_plot4(network_names[[i]])
}
```





