---
title: "Project_Plots"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---



```{r}

network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
b_list <- c(4,8)

vaccination_strategies <- c("greedy", "degree", "pagerank", "P_pagerank", "eigenvector", "betweenness")

```

# Figure 4 replication

```{r}
print_plot4 <- function(network_name,b){
  greedy <- read.csv(paste("sim2t/c2_", network_name, "_greedy_",b,"_f4.csv", sep=""))[[1]]
  degree <- read.csv(paste("sim2t/c2_", network_name, "_degree_",b,"_f4.csv", sep=""))[[1]]
  pagerank <- read.csv(paste("sim2t/c2_", network_name, "_pagerank_",b,"_f4.csv", sep=""))[[1]]
  P_pagerank <- read.csv(paste("sim2t/c2_", network_name, "_P_pagerank_",b,"_f4.csv", sep=""))[[1]]
  eigenvector <- read.csv(paste("sim2t/c2_", network_name, "_eigenvector_",b,"_f4.csv", sep=""))[[1]]
  betweenness <- read.csv(paste("sim2t/c2_", network_name, "_betweenness_",b,"_f4.csv", sep=""))[[1]]
  
  plotname <- paste(network_name,"with b=",b)
  
  ylim <- c(0, 1.0)
  plot(greedy, type = "l", col = "red", xlab = "Time Steps", ylab = "Proportion Infected", main = plotname,  ylim = ylim)
  lines(degree, col = "blue")
  lines(pagerank, col = "green")
  lines(P_pagerank, col = "orange")
  lines(eigenvector, col = "yellow")
  lines(betweenness, col = "gray")
  legend("topright", legend = c("greedy", "degree", "pagerank", "P_pagerank","eigenvector", "betweenness"), col = c("red", "blue", "green", "orange", "yellow","gray"), lty = 1,cex = 0.8)
}
```


```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
b_list <- c(4,8)

network <- "ER"
b<-4

for (network in network_names){
  for (b in b_list){
    print_plot4(network, b)
  }
}

```


# Figure 6

```{r}
print_plot6 <- function(network_name, S_prop){
  
  greedy40 <- read.csv(paste("sim2/c2_", network_name, "_greedy_40_f6.csv", sep=""))[[1]]
  greedy80 <- read.csv(paste("sim2/c2_", network_name, "_greedy_40_f6.csv", sep=""))[[1]]
  P_pagerank40 <- read.csv(paste("sim2/c2_", network_name, "_P_pagerank_40_f6.csv", sep=""))[[1]]
  P_pagerank80 <- read.csv(paste("sim2/c2_", network_name, "_P_pagerank_80_f6.csv", sep=""))[[1]]

  
  plotname <- paste(network_name,"with |S| = n *",S_prop)
  ylim <- c(0, 1.0)
  plot(greedy40, type = "l", col = "red", xlab = "Time Steps", ylab = "Proportion Infected", main = plotname, ylim = ylim)
  lines(greedy80, col = "red", lty = 2) # dotted line for greedy(b=80)
  lines(P_pagerank40, col = "blue")
  lines(P_pagerank80, col = "blue", lty = 2) # dotted line for P_pagerank(b=80)
  
  legend("topright", legend = c("greedy(b=40)", "greedy(b=80)", "P_pagerank(b=40)", "P_pagerank(b=80)"), col = c("red", "red", "blue", "blue"), lty = c(1, 2, 1, 2), cex = 0.8)
}
```


```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
S_prop <- c(0.1,0.1,0.1,0.1,0.1,0.1,0.05)


for (i in 1:length(network_names)) {
  
    print_plot6(network_names[[i]], S_prop[[i]])
}

```


# Figure 7

```{r}
print_plot7 <- function(network_name, S_prop){
  
  greedy0 <- 1-read.csv(paste("sim2/c2_", network_name, "_greedy_0_f7.csv", sep=""))[[1]]
  greedy20 <- 1-read.csv(paste("sim2/c2_", network_name, "_greedy_20_f7.csv", sep=""))[[1]]
  greedy40 <- 1-read.csv(paste("sim2/c2_", network_name, "_greedy_40_f6.csv", sep=""))[[1]]
  greedy60 <- 1-read.csv(paste("sim2/c2_", network_name, "_greedy_60_f7.csv", sep=""))[[1]]
  greedy80 <- 1-read.csv(paste("sim2/c2_", network_name, "_greedy_80_f6.csv", sep=""))[[1]]
  greedy100 <- 1-read.csv(paste("sim2/c2_", network_name, "_greedy_100_f7.csv", sep=""))[[1]]

  
  plotname <- paste(network_name,"with |S| = n *",S_prop)
  ylim <- c(0.5, 1.0)
  plot(greedy0, type = "l", col = "red", xlab = "Time Steps", ylab = "Proportion of non Infected", main = plotname, ylim = ylim)
  lines(greedy20, col = "blue")
  lines(greedy40, col = "green")
  lines(greedy60, col = "orange")
  lines(greedy80, col = "yellow")
  lines(greedy100, col = "gray")
  legend("topright", legend = c("b=0", "b=20", "b=40", "b=60","b=80", "b=100"), col = c("red", "blue", "green", "orange", "yellow","gray"), lty = 1,cex = 0.8)
}
```


```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
S_prop <- c(0.1,0.1,0.1,0.1,0.1,0.1,0.05)

for (i in 1:length(network_names)) {
  
    print_plot7(network_names[[i]], S_prop[[i]])
}

```




