---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(igraph)
```

Networks:

```{r}
set.seed(42)
n <- 1000
ER <- sample_gnm(n=n, m=1000)
BA <- barabasi.game(n, 2, directed = FALSE)
WS <- sample_smallworld(dim=1,size=n, nei=1,p=0.05)
complete_graph <- make_full_graph(n)
tree <- make_tree(n, children = 1, mode = "undirected")
```

Real networks:

#GR-QC
```{r}
edge_list <- read.csv("data/CA-GrQc.txt", sep="\t", header=FALSE, skip=4, col.names=c("FromNodeId", "ToNodeId"))
G <- graph_from_data_frame(edge_list, directed=TRUE, vertices=NULL)
# Remove self-loops and multiple edges
GR_QC <- simplify(G, remove.multiple = TRUE, remove.loops = TRUE)
```

#HEP-TH
```{r}
edge_list <- read.csv("data/CA-HepTh.txt", sep="\t", header=FALSE, skip=4, col.names=c("FromNodeId", "ToNodeId"))
G <- graph_from_data_frame(edge_list, directed=TRUE, vertices=NULL)
# Remove self-loops and multiple edges
HEP_TH <- simplify(G, remove.multiple = TRUE, remove.loops = TRUE)
```

#Facebook
```{r}
edge_list <- read.csv("data/musae_facebook_edges.csv", sep=",", header=FALSE, skip=1, col.names=c("FromNodeId", "ToNodeId"))
G <- graph_from_data_frame(edge_list, directed=TRUE, vertices=NULL)
# Remove self-loops and multiple edges
Facebook <- simplify(G, remove.multiple = TRUE, remove.loops = TRUE)

```

#Deezer
```{r}
edge_list <- read.csv("data/deezer_europe_edges.csv", sep=",", header=FALSE, skip=1, col.names=c("FromNodeId", "ToNodeId"))
G <- graph_from_data_frame(edge_list, directed=TRUE, vertices=NULL)
# Remove self-loops and multiple edges
Deezer <- simplify(G, remove.multiple = TRUE, remove.loops = TRUE)
```

#EmailEnron
```{r}
edge_list <- read.csv("data/email-Enron.txt", sep="\t", header=FALSE, skip=4, col.names=c("FromNodeId", "ToNodeId"))
G <- graph_from_data_frame(edge_list, directed=TRUE, vertices=NULL)
# Remove self-loops and multiple edges
EmailEnron <- simplify(G, remove.multiple = TRUE, remove.loops = TRUE)
```

SIS + vaccination strategy:

#Greedy strategy
```{r}
# Function to perform the greedy algorithm
greedy_algorithm <- function(G, b = round(0.1 * vcount(G)), max_walk_length = 10) {
  
  # Nested function for Monte Carlo simulation
  monte_carlo_simulation <- function(node, G, max_walk_length, num_simulations) {
    trap_count <- 0
    for (i in 1:num_simulations) {
      walk_length <- sample(1:max_walk_length, 1)
      end_node <- simulate_random_walk(node, G, walk_length)
      if (end_node == node) trap_count <- trap_count + 1
    }
    return(trap_count / num_simulations)
  }

  # Nested function to simulate a random walk from a node
  simulate_random_walk <- function(node, G, walk_length) {
    current <- node
    for (i in 1:walk_length) {
      neighbors <- neighbors(G, current)
      if (length(neighbors) == 0) break
      current <- sample(neighbors, 1)
    }
    return(current)
  }

  S <- vector("list", length = 0) # Set of nodes for traps
  node_benefits <- numeric(length = vcount(G)) # Store benefits for each node
  
  # Compute benefits for each node
  for (node in V(G)) {
    node_benefits[node] <- monte_carlo_simulation(node, G, max_walk_length, num_simulations = 100) #Set parameters
  }
  
  # Sort nodes by their benefits and select the top b nodes
  top_nodes <- order(node_benefits, decreasing = TRUE)
  S <- V(G)[top_nodes]

  return(S)
}
```

#Other strategies:

```{r}
# Function to calculate PageRank
calculate_pagerank <- function(G) {
  return(page_rank(G)$vector)
}

# Function to calculate P-pageRank
calculate_P_pagerank <- function(G, p) {
  return(page_rank(G, damping = p)$vector)
}

# Function to calculate Eigenvector Centrality
calculate_eigenvector_centrality <- function(G) {
  return(eigen_centrality(G)$vector)
}

# Function to calculate Betweenness Centrality
calculate_betweenness_centrality <- function(G) {
  return(betweenness(G))
}
```

Simulations

```{r}

network_names <- c("ER", "BA", "WS", "complete_graph", "tree","GR_QC", "HEP_TH", "Facebook", "Deezer", "EmailEnron")
networks <- list(ER, BA, WS, complete_graph, tree,GR_QC,HEP_TH, Facebook, Deezer,EmailEnron)
vaccination_strategies <- c("greedy","degree", "pagerank", "P_pagerank", "eigenvector", "betweenness", "random")

```


# Generate the selected vaccinated nodes

```{r}

get_vaccinated_nodes <- function(G, vaccination_strategy){
  if(vaccination_strategy == "greedy"){
     vaccinated_nodes <- greedy_algorithm(G)
    
  } else {
    # Calculate vaccination scores based on the chosen strategy
    vaccination_scores <- switch(
      vaccination_strategy,
      "degree" = degree(G),
      "pagerank" = calculate_pagerank(G),
      "P_pagerank" = calculate_P_pagerank(G, p = 0.15),  # You can adjust the preference parameter
      "eigenvector" = calculate_eigenvector_centrality(G),
      "betweenness" = calculate_betweenness_centrality(G),
      "random" = runif(vcount(G)),  # Random vaccination
      "greedy" = greedy_algorithm(G, b = 0.1 * vcount(G))
    )
  
    # Sort nodes by vaccination score in descending order
    sorted_nodes <- order(-vaccination_scores)
  
    # Select a fraction of nodes for vaccination
    vaccinated_nodes <- sorted_nodes[1:round(0.1 * vcount(G))]
  }
  return(vaccinated_nodes)
}

```


```{r}

for (i in 1:length(networks)) {
  G <- networks[[i]]
  network_name <- network_names[i]
  
  for (vaccination_strategy in vaccination_strategies) {
    print(paste("Generating: ", network_name,"-",vaccination_strategy))
    vaccinated_nodes <- get_vaccinated_nodes(G, vaccination_strategy)
    node_ids <- as.numeric(V(G)[vaccinated_nodes])
    df <- data.frame(node_ids)
    filename <- paste("files/", network_name, "_", vaccination_strategy, ".csv", sep="")
    
    write.csv(df, file = filename, row.names = FALSE)
  }
}

```

SIS with vaccination strategy (using S):

```{r}
random_walk_infection <- function(G, start_node,statuses, S, alpha) {
    current_node <- start_node
    walk_lengh =  rgeom(1, prob = alpha) + 1 # verificar si no falla
    for (i in 1:walk_lengh) {
        # Move to a random neighbor
        neighbors <- neighbors(G, current_node)
        if (length(neighbors) > 0) {
            current_node <- sample(neighbors, 1)
        }

        # Mark the current node as infected if it is not in S
        if (!current_node %in% S) {
            statuses[current_node] <- 1
        }
    }
    return(statuses)
}


# Function to select set S from graph G
select_nodes <- function(G, S_size, case_type) {
  if (case_type == "case1") {
    # Random selection
    S <- sample(V(G), S_size)
  } else if (case_type == "case2") {
    # Targeted selection based on a criterion, e.g., highest degree
    degree_nodes <- order(-degree(G))
    S <- V(G)[degree_nodes[1:S_size]]
  }
  return(S)
}
```


```{r}
G <- ER
case_type = "case1"
S_size <- round(S_prop[i] * vcount(G))
```


```{r}
# Extended SIS simulation function with vaccination strategy
SISsim_vaccination <- function(G, beta, gamma, vacc_nodes_file, max_steps = 100, num_vaccinated = round(0.1 * vcount(G)), case_type = "case1", alpha = 0.1, S_size = 10) {
  
  #Output initialization
  prop_infected <- numeric(max_steps)
  num_infected <- numeric(max_steps)
  
  # Choose S depending on the case being analyzed
  S <- select_nodes(G, S_size, case_type)
  statuses <- numeric(vcount(G))
  S_ids <- as.numeric(V(G)[S])
  
  # Infect the nodes
  statuses[S_ids] <- 1

  # Apply vaccination
  nodes_df <- read.csv(vacc_nodes_file, sep="\t", header=FALSE, skip=1)
  vaccinated_nodes <- nodes_df[, 1] 
  vaccinated_nodes<- na.omit(vaccinated_nodes[1:num_vaccinated])
  
  statuses[vaccinated_nodes] <- 0
  
  for (step in 1:max_steps) {
    for (node in 1:vcount(G)) {
      if (statuses[node] == 1) {
        neighbors <- neighbors(G, node)
        # Filter out neighbors that are in vaccinated_nodes
        valid_neighbors <- setdiff(neighbors, vaccinated_nodes)
        
        # Randomly select one valid neighbor
        if (length(valid_neighbors) > 0) {
            selected_neighbor <- sample(valid_neighbors, 1)
            statuses[selected_neighbor] <- 1
        }
        # Get recovered
        if (statuses[node] == 1 && runif(1) < gamma) {
          statuses[node] <- 0
        }
      }
    }
    
    num_infected[step] <- sum(statuses)
    prop_infected[step] <- sum(statuses) / vcount(G)
  }
  
  return(list(num_infected = num_infected, prop_infected = prop_infected[1:step]))
}
```

# Case 1

```{r}
# Create the 'sim' directory if it doesn't exist
if (!file.exists("sim")) {
  dir.create("sim")
}
```

```{r}
# Function to calculate the average of a list of numeric vectors
average_vector_list <- function(list_of_vectors) {
    sum_vector <- Reduce(`+`, list_of_vectors)
    avg_vector <- sum_vector / length(list_of_vectors)
    return(avg_vector)
}
```

```{r}
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
networks <- list(ER, BA, WS, complete_graph, tree, GR_QC, HEP_TH)
vaccination_strategies <- c("greedy", "degree", "pagerank", "P_pagerank", "eigenvector", "betweenness")
alphas <- c(0.1, 0.3)
beta <- 0.6
gamma <- 0.4 


for (network_idx in 1:length(networks)) {
    G <- networks[[network_idx]]
    network_name <- network_names[network_idx]

    for (vaccination_strategy in vaccination_strategies) {
        vacc_nodes_file <- paste("files/", network_name, "_", vaccination_strategy, ".csv", sep="")

        for (num_vaccinated in seq(4, 20, by = 4)) {
            for (alpha in alphas) {
              
               S_size <- round(0.1 * vcount(G)) 
               
               avg_prop_infected_list <- list()
               avg_num_infected_list <- list()

               # Execute SISsim_vaccination 5 times
               for (sim_run in 1:5) {
                   res <- SISsim_vaccination(G, beta, gamma, vacc_nodes_file, max_steps = 100, 
                                             num_vaccinated = num_vaccinated, case_type = "case1", alpha = alpha, S_size = S_size)
                   # Accumulate results for averaging
                   avg_prop_infected_list[[sim_run]] <- res$prop_infected
                  avg_num_infected_list[[sim_run]] <- res$num_infected
               }
  
               # Average the results
               avg_prop_infected <- average_vector_list(avg_prop_infected_list)
               avg_num_infected <- average_vector_list(avg_num_infected_list)
               
               out_filename = paste("sim/c1_", network_name, "_", vaccination_strategy,"_",num_vaccinated,"_",alpha, ".csv", sep="")
               result_df <- data.frame(avg_prop_infected, avg_num_infected)
               write.csv(result_df, file = out_filename, row.names = FALSE)
            }
        }
    }
}

```


# Case 2

# Figure 4
```{r}

case_type = "case2"

network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
networks <- list(ER, BA, WS, complete_graph, tree, GR_QC, HEP_TH)
vaccination_strategies <- c("greedy", "degree", "pagerank", "P_pagerank", "eigenvector", "betweenness")
alpha <- 0.1
beta <- 0.6
gamma <- 0.4 


for (network_idx in 1:length(networks)) {
    G <- networks[[network_idx]]
    network_name <- network_names[network_idx]

    for (vaccination_strategy in vaccination_strategies) {
        vacc_nodes_file <- paste("files/", network_name, "_", vaccination_strategy, ".csv", sep="")

        # for (num_vaccinated in c(4,8)) {
        for (num_vaccinated in c(4)) {
          
             out_filename = paste("sim2/c2_", network_name, "_", vaccination_strategy,"_",num_vaccinated,"_f4.csv", sep="")
             
             if (file.exists(out_filename)) {
                  # If the file exists, skip to the next iteration
                  next
              }
             print(paste("Generating: ",out_filename))
             
             S_size <- round(0.1 * vcount(G)) #no estoy seguro
            
             avg_prop_infected_list <- list()
             avg_num_infected_list <- list()

             # Execute SISsim_vaccination 5 times
             for (sim_run in 1:5) {
                 res <- SISsim_vaccination(G, beta, gamma, vacc_nodes_file, max_steps = 100, 
                                             num_vaccinated = num_vaccinated, case_type = case_type, alpha = alpha, S_size = S_size)
                 # Accumulate results for averaging
                 avg_prop_infected_list[[sim_run]] <- res$prop_infected
                  avg_num_infected_list[[sim_run]] <- res$num_infected
             }

             # Average the results
             avg_prop_infected <- average_vector_list(avg_prop_infected_list)
             avg_num_infected <- average_vector_list(avg_num_infected_list)
             
             
             result_df <- data.frame(avg_prop_infected, avg_num_infected)
             write.csv(result_df, file = out_filename, row.names = FALSE)
        }
    }
}
```


# Figure 6
```{r}
case_type = "case2"
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
networks <- list(ER, BA, WS, complete_graph, tree, GR_QC, HEP_TH)
S_prop <- c(0.1,0.1,0.1,0.1,0.1,0.1,0.05)
vaccination_strategies <- c("greedy", "P_pagerank")
alpha <- 0.1
beta <- 0.6
gamma <- 0.4 


for (network_idx in 1:length(networks)) {
    G <- networks[[network_idx]]
    network_name <- network_names[network_idx]

    for (vaccination_strategy in vaccination_strategies) {
        vacc_nodes_file <- paste("files/", network_name, "_", vaccination_strategy, ".csv", sep="")

        for (num_vaccinated in c(40,80)) {
          
             out_filename = paste("sim2t/c2_", network_name, "_", vaccination_strategy,"_",num_vaccinated,"_f6.csv", sep="")
             
             if (file.exists(out_filename)) {
                  # If the file exists, skip to the next iteration
                  next
              }
             print(paste("Generating: ",out_filename))
             
             S_size <- round(S_prop[i] * vcount(G)) #no estoy seguro
            
             avg_prop_infected_list <- list()
             avg_num_infected_list <- list()

             # Execute SISsim_vaccination 5 times
             for (sim_run in 1:5) {
                 res <- SISsim_vaccination(G, beta, gamma, vacc_nodes_file, max_steps = 100, 
                                             num_vaccinated = num_vaccinated, case_type = case_type, alpha = alpha, S_size = S_size)
                 # Accumulate results for averaging
                 # Append results to the lists
                  avg_prop_infected_list[[sim_run]] <- res$prop_infected
                  avg_num_infected_list[[sim_run]] <- res$num_infected
             }

             # Average the results
             avg_prop_infected <- average_vector_list(avg_prop_infected_list)
             avg_num_infected <- average_vector_list(avg_num_infected_list)
             
             
             result_df <- data.frame(avg_prop_infected, avg_num_infected)
             write.csv(result_df, file = out_filename, row.names = FALSE)
        }
    }
}
```


# Figure 7
```{r}
case_type = "case2"
network_names <- c("ER", "BA", "WS", "complete_graph", "tree", "GR_QC", "HEP_TH")
networks <- list(ER, BA, WS, complete_graph, tree, GR_QC, HEP_TH)
S_prop <- c(0.1,0.1,0.1,0.1,0.1,0.1,0.05)
vaccination_strategies <- c("greedy")
alpha <- 0.1
beta <- 0.6
gamma <- 0.4 


for (network_idx in 1:length(networks)) {
    G <- networks[[network_idx]]
    network_name <- network_names[network_idx]

    for (vaccination_strategy in vaccination_strategies) {
        vacc_nodes_file <- paste("files/", network_name, "_", vaccination_strategy, ".csv", sep="")

        for (num_vaccinated in c(0,20,60,100)) {
          
             out_filename = paste("sim2/c2_", network_name, "_", vaccination_strategy,"_",num_vaccinated,"_f7.csv", sep="")
             
             if (file.exists(out_filename)) {
                  # If the file exists, skip to the next iteration
                  next
              }
             print(paste("Generating: ",out_filename))
             
             S_size <- round(S_prop[i] * vcount(G)) #no estoy seguro
            
             avg_prop_infected_list <- list()
             avg_num_infected_list <- list()

             # Execute SISsim_vaccination 5 times
             for (sim_run in 1:5) {
                 res <- SISsim_vaccination(G, beta, gamma, vacc_nodes_file, max_steps = 100, 
                                             num_vaccinated = num_vaccinated, case_type = case_type, alpha = alpha, S_size = S_size)
                 # Accumulate results for averaging
                 avg_prop_infected_list[[sim_run]] <- res$prop_infected
                  avg_num_infected_list[[sim_run]] <- res$num_infected
             }

             # Average the results
             avg_prop_infected <- average_vector_list(avg_prop_infected_list)
             avg_num_infected <- average_vector_list(avg_num_infected_list)
             
             
             result_df <- data.frame(avg_prop_infected, avg_num_infected)
             write.csv(result_df, file = out_filename, row.names = FALSE)
        }
    }
}
```


```{r}
case_type = "case2"
network_names <- c("BA")
networks <- list(ER, BA, WS, complete_graph, tree)
S_prop <- c(0.1,0.1,0.1,0.1,0.1)
vaccination_strategies <- c("greedy", "degree", "pagerank", "P_pagerank", "eigenvector", "betweenness")
alpha <- 0.1
beta <- 0.6
gamma <- 0.4 
num_vaccinated <- 80

for (network_idx in 1:length(networks)) {
    G <- networks[[network_idx]]
    network_name <- network_names[network_idx]

    for (vaccination_strategy in vaccination_strategies) {
        vacc_nodes_file <- paste("files/", network_name, "_", vaccination_strategy, ".csv", sep="")

             out_filename = paste("sim2/c2_", network_name, "_", vaccination_strategy,"_",num_vaccinated,"_s10000.csv", sep="")
             
             if (file.exists(out_filename)) {
                  # If the file exists, skip to the next iteration
                  next
              }
             print(paste("Generating: ",out_filename))
             
             S_size <- round(S_prop[i] * vcount(G)) #no estoy seguro
            
             avg_prop_infected_list <- list()
             avg_num_infected_list <- list()

             # Execute SISsim_vaccination 5 times
             for (sim_run in 1:3) {
                 res <- SISsim_vaccination(G, beta, gamma, vacc_nodes_file, max_steps = 10000, 
                                             num_vaccinated = num_vaccinated, case_type = case_type, alpha = alpha, S_size = S_size)
                 # Accumulate results for averaging
                 avg_prop_infected_list[[sim_run]] <- res$prop_infected
                  avg_num_infected_list[[sim_run]] <- res$num_infected
             }

             # Average the results
             avg_prop_infected <- average_vector_list(avg_prop_infected_list)
             avg_num_infected <- average_vector_list(avg_num_infected_list)
             
             
             result_df <- data.frame(avg_prop_infected, avg_num_infected)
             write.csv(result_df, file = out_filename, row.names = FALSE)
    }
}
```
